apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-app
  template:
    metadata:
      labels:
        app: expense-tracker-app
    spec:
      containers:
        - name: app
          image: laly9999/expense-tracker-app:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: expense-tracker-db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_DATABASE
